{
    'name': 'IET Project System',
    'version': '1.0',
    'depends': ['project','iet_custom_project','hr', 'hr_timesheet'],
     "website": "https://intelligent-experts.com/en/home/",
    'auther': 'IET - SalehElSrief',
    'category': 'Project',
    'description': 'Add Project Plan tab with tasks and milestones',
    'data': [
        'security/project_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/project_project_views.xml',
        'views/project_task_type.xml',
        'views/project_task.xml',
        'views/business_tasks.xml',
        'views/development_tasks.xml',
        'views/project_scope.xml',
        'wizard/import_project_plan.xml',
    ],
    'installable': True,
    'application': False,
}
